про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [2]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

С чем мы работаем?

In [4]:
vec.dtype

dtype('int64')

Размер массива:

In [5]:
vec.shape

(3, 2)

Число осей:

In [6]:
vec.ndim

2

У некоторых функций бывает параметр axis, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [7]:
np.sum(vec)

21

In [8]:
np.sum(vec, axis=0)

array([ 9, 12])

In [9]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [10]:
vec.sum()

21

Транспонируем массив:

In [12]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [13]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная vec не поменялась!

In [14]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [15]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [18]:
vec[:, 1]

array([2, 4, 6])

In [19]:
vec[2, :]

array([5, 6])

In [20]:
vec[1:2, 0]

array([3])

In [21]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [22]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [23]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [25]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [33]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [29]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [30]:
vec + 1
vec * 2
vec ** 2
vec + vec ** 2
vec * vec ** 2
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

In [34]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [35]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [36]:
np.random.rand(2, 3)
np.random.seed(2019)
np.random.rand(2, 3)
np.random.randn(3, 2)
np.random.normal(2, 1, size=3)
np.random.randint(5, 10, size=3)

array([8, 6, 8])

Почему вообще используют numpy?

In [37]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

UsageError: Line magic function `%%time` not found.



# Task 2

Задания для самостоятельного решения

Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).

Найти максимальный нечетный элемент в массиве.

Замените все нечетные элементы массива на ваше любимое число.

Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если n=5, то ответом будет array([9, 7, 5, 3, 1]). 

Функции, которые могут пригодиться при решении: .arange()

Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив array([0, 1, 2, 3, 4]) и число 1.33, то ответом будет (1, 4). Функции, которые могут пригодиться при решении: .abs(), .argmax(), .argmin()

Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов array([4, 6, 0, 1]), что соответствует полиному 4x3+6x2+1, на выходе получается массив коэффициентов array([1, 2, 0, 1, -2]), соответствующий полиному x4+2x3+x−2. Функции, которые могут пригодиться при решении: .append()
Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.